ITEM_TITLE: "Building an AI Recruiter, Drupal 11 Automation, and Life on the Water"
ITEM_DESCRIPTION: "Dan walks through building an AI-powered recruiter automation system, advanced Drupal 11 workflow techniques, and lessons learned from weekend boating in coastal Delaware."
ITEM_SUBTITLE: "AI automation, Drupal architecture, and coastal lifestyle insights"
CATEGORIES:
  - "Science and Technology"
  - "Arts and Culture"

PODCAST_BLOCK_01_START_TIME: 0
PODCAST_BLOCK_01_TITLE: "Opening Monologue and Episode Overview"

PODCAST_COMMERCIAL_BLOCK_01_START_TIME: 420
PODCAST_COMMERCIAL_BLOCK_01_TITLE: "Sponsor Message: Xandermar AI Solutions"

PODCAST_BLOCK_02_START_TIME: 540
PODCAST_BLOCK_02_TITLE: "Designing an AI Recruiter Platform"

PODCAST_COMMERCIAL_BLOCK_02_START_TIME: 1680
PODCAST_COMMERCIAL_BLOCK_02_TITLE: "Sponsor Message: Cloud Hosting and DevOps Stack"

PODCAST_BLOCK_03_START_TIME: 1800
PODCAST_BLOCK_03_TITLE: "Drupal 11 Automation and Workflow Engineering"

PODCAST_BLOCK_04_START_TIME: 3120