ITEM_TITLE: "The 50 Shades of Beer Podcast — Series Introduction"
ITEM_DESCRIPTION: "An energetic introduction to The 50 Shades of Beer Podcast — a show blending current events, political satire, trending topics, technology, media narratives, and unfiltered opinion. This kickoff episode explains the show's premise, tone, recurring segments, and what listeners can expect each week."
ITEM_SUBTITLE: "Where headlines breathe and the conversation is always on tap."
CATEGORIES: [
  "News Commentary",
  "Satire",
  "Politics",
  "Culture",
  "Opinion",
  "Trending Topics",
  "Podcast Launch"
]

PODCAST_BLOCK_01_START_TIME: "00:00"
PODCAST_BLOCK_01_TITLE: "Welcome & Show Premise — Why This Podcast Exists"