ITEM_TITLE: "AI Job Automation, Drupal 11 Tips, and RV Road Trips"
ITEM_DESCRIPTION: "Dan explores AI-powered job automation, practical Drupal 11 architecture tips, and lessons learned from RV travel across the country."
ITEM_SUBTITLE: "Automation, Drupal engineering, and life on the road"
CATEGORIES:
  - "Technology"
  - "Travel"

PODCAST_BLOCK_01_START_TIME: 120
PODCAST_BLOCK_01_TITLE: "AI Job Automation"

PODCAST_COMMERCIAL_BLOCK_01_START_TIME: 420
PODCAST_COMMERCIAL_BLOCK_01_TITLE: "Sponsor message — Xandermar AI services"

PODCAST_BLOCK_02_START_TIME: 540
PODCAST_BLOCK_02_TITLE: "Drupal 11 Tips"

PODCAST_COMMERCIAL_BLOCK_02_START_TIME: 1500
PODCAST_COMMERCIAL_BLOCK_02_TITLE: "Cloudflare R2 podcast hosting promo"

PODCAST_BLOCK_03_START_TIME: 1620
PODCAST_BLOCK_03_TITLE: "RV Road Trips"

PODCAST_BLOCK_04_START_TIME: 2580